spin_version = "1"
authors = ["Rogelio Morrell"]
name = "@fairdatasociety/personal-smart-contracts"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "hello"
source = "target/spin-http-js.wasm"
files = ["src/index.html"]
[component.trigger]
route = "/hello"
[component.build]
command = "npm run build"
